spring:

  application:
    name: Ecommerce
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_db
    username: root
    password: Dairymilk@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 618095817112-qj8ebfrg6gfs1hdq0oi5nb6ol6mlkvr9.apps.googleusercontent.com
            client-secret: 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
          github:
            client-id: Iv23liEzO1O3PiF8R07j
            client-secret: Ca4BRa3SPhCgetnBX2UlrTeQKZlciDV9CEzsM7WGq9w=
  mail:
    host: smtp.gmail.com
    port: 587
    username: Mohit4rudrakar@gmail.com
    password: jtrujzbirgaopqeo
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

app:
  jwtSecret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  cloudinary:
    cloud-name: dsxiuwfgh
    api-key: 913641382464613
    api-secret: HbaYk_0PXL8bQKPXPcKqOB2Few4
  gemini:
    api-key: AIzaSyBpoaDpGLWQOppkNtV-nxQ7AoFAdTitf18

